name: Release

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    uses: Aegolius-Labs/.github/.github/workflows/conventional-release.yml@main
